# Numpy

#### The fundamental package for scientific computing with Python

https://numpy.org/



In [1]:
!pip install numpy

### Numpy Arrays

2 types

* Vectors


* Matrices

### Creating Numpy Arrays

In [2]:
my_list = [1,2,3]

my_list

[1, 2, 3]

In [3]:
type(my_list)

list

### Import Numpy

In [4]:
import numpy as np # Alias = np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
type(my_matrix)

list

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in methods of numpy

#### arange

Returns evenly spaced values within a given interval

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### Zeros and Ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace

Returns evenly spaced numbers over specified interval

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

#### eye

Generate identity matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

create random arrays

#### rand

Creates an array of given shape and populate it with random samples with uniform distribution over [0,1]

In [20]:
np.random.rand(3)

array([0.7075368 , 0.09284324, 0.95803568])

In [21]:
np.random.rand(3,3)

array([[0.78808022, 0.55529995, 0.62743513],
       [0.82419449, 0.45342226, 0.32651851],
       [0.96039095, 0.02804405, 0.60682056]])

#### randn

Returns a sample from standard normal distribution

In [22]:
np.random.randn(2)

array([-0.18844897,  1.20029664])

In [23]:
np.random.randn(5,5)

array([[ 0.53531537,  0.65902432,  2.23754465, -0.81286806, -0.19248298],
       [ 0.33119745,  0.87128563,  0.2418411 , -0.39328999, -0.53851007],
       [ 0.89106303, -0.19570886,  0.48061336,  1.55206224,  0.06742757],
       [-0.49197624,  0.55866782, -0.13333559,  0.41585872, -0.03330311],
       [-0.45396536, -0.59467959,  1.22923148, -0.89107421,  1.38545813]])

#### randint

Random integers

In [24]:
np.random.randint(5)

2

In [27]:
np.random.randint(1,10,3)

array([4, 3, 5])

#### Array attributes and methods

In [28]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
myarr = np.random.randint(0,50,10)
myarr

array([38, 41, 30, 40, 28, 21, 16, 36, 25, 46])

In [31]:
arr.shape

(25,)

#### max, min, argmax, argmin

In [33]:
myarr.max()

46

In [34]:
myarr.min()

16

In [35]:
myarr.argmax()

9

In [36]:
myarr.argmin()

6

### Shape / Reshape

In [37]:
arr.shape

(25,)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr2=arr.reshape(5,5)

In [41]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr2.shape

(5, 5)

In [44]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

#### dtype

find type of variables in array

In [45]:
arr.dtype

dtype('int64')

# Great Job !